version: '3.1'

services:
  collector:
    build: .
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - API_USERNAME=${API_USERNAME}
      - API_PASSWORD=${API_PASSWORD}
      - API_OTP=${API_OTP}
      - API_LOGIN_URL=${API_LOGIN_URL}
      - API_DEVICE_URL=${API_DEVICE_URL}
      - MYSQL_HOST=db
    depends_on:
      - db

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    volumes:
      - vol-db:/var/lib/mysql

volumes:
  vol-db:
