version: '3.1'

services:
  db:
    image: mysql-server:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 55mySQL364!

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1