version: '3.1'

services:
  adminer:
    image: adminer
    ports:
      - 8080:8080
    restart: unless-stopped

  db:
    image: mysql/mysql-server:5.7
    volumes:
      - vol-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD:    ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE:         ${MYSQL_DATABASE}
      MYSQL_USER:             ${MYSQL_USER}
      MYSQL_PASSWORD:         ${MYSQL_PASSWORD}
    restart: always

volumes:
  vol-db:
